/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually

    tutorialSidebar: [ 
        'intro',
        {
            type: 'category',
            label: 'neovim',
            link: {type: 'doc', id: 'tutorial-neovim/intro'},
            items: [
                'tutorial-neovim/vi',
                'tutorial-neovim/config',
            ],
        },
        {
            type: 'category',
            label: 'tmux',
            link: {type: 'doc', id: 'tutorial-tmux/intro'},
            items: [
            ],
        },
        {
            type: 'category',
            label: 'Github Pages + Docusaurus',
            link: {type: 'doc', id: 'tutorial-setting/intro'},
            items: [
            ],
        },
        {
            type: 'category',
            label: 'Theory of Computation',
            link: {type: 'doc', id: 'tutorial-formal/intro'},
            items: [
            ],
        },
        {
            type: 'category',
            label: 'Deep Learning',
            link: {type: 'doc', id: 'tutorial-dl/intro'},
            items: [
            ],
        },
    ],

};

module.exports = sidebars;
